#
# Copyright (C) 2012 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

permissions: {}

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'DEVELOPING.md'
    - 'LICENSE'
    - 'README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - 'DEVELOPING.md'
    - 'LICENSE'
    - 'README.md'

jobs:
  call-maven-ci:
    if: github.repository == 'project-ncl/pom-manipulation-ext' && github.event_name == 'pull_request'
    strategy:
      fail-fast: false
      matrix:
        maven-version: [3.6.3, 3.8.7, 3.9.0, 3.9.8]
        java-version: ['11']
        build-command: ['mvn -B -V clean install -Prun-its']
        # Use include to add a specific Maven/JDK/Build-command combination
        include:
          - maven-version: 3.3.9
            java-version: '11'
            build-command: "mvn -B -V clean install -Prun-its -Pearly-maven"
          - maven-version: 3.5.4
            java-version: '11'
            build-command: "mvn -B -V clean install -Prun-its -Pearly-maven"
          - maven-version: 3.9.11
            java-version: '17'
            build-command: "mvn -B -V clean install -Prun-its"
          - maven-version: 3.9.15
            java-version: '17'
            build-command: "mvn -B -V clean install -Prun-its"
    uses: project-ncl/shared-github-actions/.github/workflows/maven-ci.yml@ef31e53140344cac0421b7211cc0940182409106 # v0.0.16
    with:
      build_command: ${{ matrix.build-command }}
      java_version: ${{ matrix.java-version }}
      maven_version: ${{ matrix.maven-version }}
  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
